include: package:very_good_analysis/analysis_options.5.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    prefer_single_quotes: false
analyzer:
  exclude:
    - lib/src/data/dtos/tickets/*.g.dart
    - lib/src/data/dtos/identity/*.g.dart
    - lib/src/data/dtos/user/*.g.dart
    - lib/src/data/dtos/user/*.freezed.dart
  errors:
    invalid_annotation_target: ignore
