// Mocks generated by Mockito 5.4.4 from annotations
// in task_manager_app/test/unit_tests/task_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i9;
import 'package:task_manager_app/core/data/data_source/local/task_database.dart'
    as _i8;
import 'package:task_manager_app/features/task/data/dto/add_task.dto.dart'
    as _i6;
import 'package:task_manager_app/features/task/data/dto/task_dto.dart' as _i5;
import 'package:task_manager_app/features/task/data/dto/update_task_dto.dart'
    as _i7;
import 'package:task_manager_app/features/task/data/model/task/task.dart'
    as _i2;
import 'package:task_manager_app/features/task/repository/task_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTask_0 extends _i1.SmartFake implements _i2.Task {
  _FakeTask_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i3.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Task>> getUserTasks(_i5.TaskDto? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserTasks,
          [params],
        ),
        returnValue: _i4.Future<List<_i2.Task>>.value(<_i2.Task>[]),
      ) as _i4.Future<List<_i2.Task>>);

  @override
  _i4.Future<_i2.Task> addTask(_i6.AddTaskDto? params) => (super.noSuchMethod(
        Invocation.method(
          #addTask,
          [params],
        ),
        returnValue: _i4.Future<_i2.Task>.value(_FakeTask_0(
          this,
          Invocation.method(
            #addTask,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Task>);

  @override
  _i4.Future<void> updateTask(_i7.UpdateTaskDto? params) => (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [params],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteTask() => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [TaskDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskDatabase extends _i1.Mock implements _i8.TaskDatabase {
  MockTaskDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> createTable(_i9.Database? database) => (super.noSuchMethod(
        Invocation.method(
          #createTable,
          [database],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cacheTasks(List<_i2.Task>? tasks) => (super.noSuchMethod(
        Invocation.method(
          #cacheTasks,
          [tasks],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearDatabase() => (super.noSuchMethod(
        Invocation.method(
          #clearDatabase,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> addTask(_i2.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #addTask,
          [task],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> updateTask(_i2.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #updateTask,
          [task],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> deleteTask(_i2.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #deleteTask,
          [task],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i2.Task>> getAllTasks() => (super.noSuchMethod(
        Invocation.method(
          #getAllTasks,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Task>>.value(<_i2.Task>[]),
      ) as _i4.Future<List<_i2.Task>>);
}
